services:
  pool:
    build:
      context: ./pool
    env_file:
      - ./env/.env
    ports:
      - "2018:2018"
      - "8081:8080"
    volumes:
      - pool_data:/data
    restart: unless-stopped
    networks:
      umbrel_main_network:
        aliases:
          - pool

  dashboard:
    build:
      context: ./dashboard
    ports:
      - "3334:80"
    restart: unless-stopped
    depends_on:
      - pool
    networks:
      umbrel_main_network:

networks:
  umbrel_main_network:
    external: true

volumes:
  pool_data:
